local RemoteNames = {
	RequestBuyCosmetic   = "RequestBuyCosmetic",
	RequestEquipCosmetic = "RequestEquipCosmetic",
	RequestQuestAction   = "RequestQuestAction",
	WeatherStateUpdated  = "WeatherStateUpdated",
	PlayerStateUpdated   = "PlayerStateUpdated",
	StoryStateUpdated    = "StoryStateUpdated",
	ShowDialogue         = "ShowDialogue",
	LevelComplete        = "LevelComplete",
}

return RemoteNames
